"""add database summary table and indexes

Revision ID: 5382abda7788
Revises: 9c4d9d5c3e2a
Create Date: 2026-07-27 17:25:34.863173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5382abda7788'
down_revision: Union[str, None] = '9c4d9d5c3e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pangbanksummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('collection_count', sa.Integer(), nullable=False),
    sa.Column('release_count', sa.Integer(), nullable=False),
    sa.Column('pangenome_count', sa.Integer(), nullable=False),
    sa.Column('genome_count', sa.Integer(), nullable=False),
    sa.Column('species_count', sa.Integer(), nullable=False),
    sa.Column('genus_count', sa.Integer(), nullable=False),
    sa.Column('family_count', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('class_count', sa.Integer(), nullable=False),
    sa.Column('phylum_count', sa.Integer(), nullable=False),
    sa.Column('domain_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collectionrelease_collection_latest', 'collectionrelease', ['collection_id', 'latest'], unique=False)
    op.create_index('ix_genomepangenomelink_pangenome_genome', 'genomepangenomelink', ['pangenome_id', 'genome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genomepangenomelink_pangenome_genome', table_name='genomepangenomelink')
    op.drop_index('ix_collectionrelease_collection_latest', table_name='collectionrelease')
    op.drop_table('pangbanksummary')
    # ### end Alembic commands ###
