"""Add new optional columns in Genome table

Revision ID: 765d642f1d8c
Revises: 1b2d64350ce4
Create Date: 2026-04-03 15:39:19.160477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '765d642f1d8c'
down_revision: Union[str, None] = '1b2d64350ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genome', sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('genome', sa.Column('ncbi_genome_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('genome', sa.Column('genome_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('genome', sa.Column('checkm2_completeness', sa.Float(), nullable=True))
    op.add_column('genome', sa.Column('checkm2_contamination', sa.Float(), nullable=True))
    op.add_column('genome', sa.Column('checkm2_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('genome', sa.Column('checkm_completeness', sa.Float(), nullable=True))
    op.add_column('genome', sa.Column('checkm_contamination', sa.Float(), nullable=True))
    op.add_column('genome', sa.Column('checkm_strain_heterogeneity', sa.Float(), nullable=True))
    op.add_column('genome', sa.Column('gc_count', sa.Integer(), nullable=True))
    op.add_column('genome', sa.Column('gc_percentage', sa.Float(), nullable=True))
    op.add_column('genome', sa.Column('genome_size', sa.Integer(), nullable=True))
    op.add_column('genome', sa.Column('l50_contigs', sa.Integer(), nullable=True))
    op.add_column('genome', sa.Column('n50_contigs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genome', 'n50_contigs')
    op.drop_column('genome', 'l50_contigs')
    op.drop_column('genome', 'genome_size')
    op.drop_column('genome', 'gc_percentage')
    op.drop_column('genome', 'gc_count')
    op.drop_column('genome', 'checkm_strain_heterogeneity')
    op.drop_column('genome', 'checkm_contamination')
    op.drop_column('genome', 'checkm_completeness')
    op.drop_column('genome', 'checkm2_model')
    op.drop_column('genome', 'checkm2_contamination')
    op.drop_column('genome', 'checkm2_completeness')
    op.drop_column('genome', 'genome_category')
    op.drop_column('genome', 'ncbi_genome_category')
    op.drop_column('genome', 'accession')
    # ### end Alembic commands ###
