"""Add fluidity columns to Pangenome table

Revision ID: fd73e89e68ea
Revises: 
Create Date: 2025-07-04 17:28:43.574190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd73e89e68ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pangenome', sa.Column('all_genome_fluidity', sa.Float(), nullable=True))
    op.add_column('pangenome', sa.Column('shell_genome_fluidity', sa.Float(), nullable=True))
    op.add_column('pangenome', sa.Column('cloud_genome_fluidity', sa.Float(), nullable=True))
    op.add_column('pangenome', sa.Column('accessory_genome_fluidity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pangenome', 'accessory_genome_fluidity')
    op.drop_column('pangenome', 'cloud_genome_fluidity')
    op.drop_column('pangenome', 'shell_genome_fluidity')
    op.drop_column('pangenome', 'all_genome_fluidity')
    # ### end Alembic commands ###
